### ISSUE TITLE
Python (PyPI) ecosystem support

### ISSUE THREAD

**Issue by KyeRussell** [KyeRussell/boomgate#1]
Support analysing packages in the Python (PyPI) ecosystem

### Required
- [ ] Find specific package + version in PyPI when directed
- [ ] Interpret 'extras' (e.g. `Django[argon2]`)
- [ ] Parse common Python dependency definition formats:
  - [ ] `requirements.txt`
  - [ ] `pyproject.toml`
  - [ ] `Pipfile` / `Pipfile.lock`

### Nice-to-have
- [ ] Custom PyPI repositories
- [ ] Non-PyPI dependency locations (e.g. `git`, `https`)
